"""add unique constraint owner_id + name

Revision ID: 104c34c5c442
Revises: 9dd927cfc611
Create Date: 2026-03-02 22:55:49.541515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104c34c5c442'
down_revision: Union[str, Sequence[str], None] = '9dd927cfc611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_owner_name', 'project', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_owner_name', 'project', type_='unique')
    # ### end Alembic commands ###
