"""add user role

Revision ID: d461a8fc68cd
Revises: 104c34c5c442
Create Date: 2026-03-04 23:01:11.946376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd461a8fc68cd'
down_revision: Union[str, Sequence[str], None] = '104c34c5c442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum("admin", "user", name="user_role")
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', sa.Enum('admin', 'user', name='user_role'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    sa.Enum('admin', 'user', name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
